### ISSUE TITLE
test fails

### ISSUE THREAD

**Issue by kirkins** [PsychicCat/monero-nodejs#4] opened 2016-08-09 20:33 UTC
I have the dameon and simplewallet running on my Ubuntu server.

`git clone https://github.com/PsychicCat/monero-nodejs.git`

`cd monero-nodejs`

`sudo npm install`

`sudo npm test`

And I get back:

>   moneroWallet
>     constructor
>       ✓ should have default host set to `127.0.0.1`
>       ✓ should have default port set to 18082
>     methods
>       balance()
>         1) should retrieve the account balance
>       address()
>         ✓ should return the account address
>       transfer()
>         ✓ should return a tx hash, or an error message
> 
>  4 passing (2s)
>   1 failing
> 
>   1) moneroWallet methods balance() should retrieve the account balance:
>      Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

**Comment by PsychicCat** [comment] 2016-08-10 00:38
Hm, checking on this. Only 1 method failed so it is communicating with your wallet fine. 

In the meantime, maybe run this script and see what you get back?

```
var Wallet = require('monero-nodejs');
var wallet = new Wallet();

wallet.balance().then(function(result){
    console.log(result);
});
```

**Comment by PsychicCat** [comment] 2016-08-10 02:50
@kirkins closing this because the test do pass, indicating you are communicating with your wallet in RPC mode. i updated the library, removing the transfer method from the tests (i don't want people accidentally sending me money without knowing).

**Closed as completed by PsychicCat** 2016-08-10 02:50 UTC

**Comment by kirkins** [comment] 2016-08-10 03:05
When I run 'node index.js' (with code you provided) I get back: 

{ [Error: connect ECONNREFUSED 127.0.0.1:18082]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 18082 }
`

**Comment by PsychicCat** [comment] 2016-08-10 03:10
ok, so that looks like your wallet cannot be reached at that port.

did you --rpc-bind-port when you start simplewallet?

for example:
`./simplewallet --wallet-file mywallet.bin --password "superstrongpassword" --rpc-bind-port 18082`

**Comment by kirkins** [comment] 2016-08-10 03:15
I wasn't using --rpc-bind-port

Now that I am it seems to be working perfectly. Thanks

**Comment by micodebox** [comment] 2018-01-16 18:03
hi, I am using Windows.
how can I use rpc-bind-port?

**Comment by 5-digits** [comment] 2018-03-12 09:30
The Issue is :  How to fix it on Windows  ( ` Error: connect ECONNREFUSED 127.0.0.1:18082` )

**Comment by micodebox** [comment] 2018-03-12 12:00
Yes, correct
